version: '3.1'

services:
  cvp:
    environment:
      PYTHONPATH: $PYTHONPATH:/usr/src/cvp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src
    ports:
      - 8888:8888
